format:
  html: {toc: true, toc-depth: 4, theme: cosmo}
  revealjs: {theme: cosmo, navigation-mode: vertical, transition: slide, background-transition: fade, incremental: true}
project: {type: book}
book:
  title: Support Vector Machine
  chapters: [index.qmd, assignment.islp_9_5.qmd, notebooks/python/problem9-5.ipynb, assignment.islp_9_7.qmd, notebooks/python/problem9-8.ipynb]
