
---
format:
  html: {toc: true, toc-depth: 4, theme: spacelab, output-file: index.html}
code-block-background: true
include-in-header: {text: '<link rel = "icon" href = "data:," />'}

---
<style></style><style>.printedClojure .sourceCode {
  background-color: transparent;
  border-style: none;
}
</style>
<script src="index_files/md-default0.js" type="text/javascript"></script><script src="index_files/md-default1.js" type="text/javascript"></script>

::: {.sourceClojure}
```clojure
(ns index)
```
:::



# Support Vector Machines


### **Assignment Setup**


* Create a new repository on Gitlab.com. The repository MUST be named following the convention: `CS[AAAA]_[XX][YYYY]_A[ZZ]_G[NN]` where `[AAAA]` is replaced by the four digit course number (if this is a cross-listed 4000/5000 level course, use the 4000 level number), `[XX]` is replaced with the semester (FA, SP, or SU), `[YYYY]` is replaced with the four digit year, `[ZZ]` is replaced with the two digit assignment number, `[NN]` is replaced with the two digit group number, and [LASTNAME] is replaced with your last name. **Assignments that are misnamed will be given 0 credit**!
* You may work in a group of 1 if you choose.
* Add greenr@bgsu.edu and the TA (if there is one) to your project with Maintainer project access
* Setup your project appropriately for this assignment:
* A `README.md` file in the root of the project
* A Jupyter notebook or main file that contains all of your work in a clear and understandable manner.
* You may work by yourself or in a group of 2. if working in a group of 2, each student should perform the implementation and analysis of a single algorithm.


### **Instructions**

* In a Jupyter notebook using Python, complete exercise `9.5`, `9.7`, and `9.8` (Applied) from Introduction to Statistical Learning with Applications in Python.
* Modify the "README.md" file to include responses as indicated by each question.
* Make sure that your README file is formatted properly and is visually appealing. It should be free of grammatical errors, punctuation errors, capitalization issues, etc. Sentences should be complete


```{=html}
<div style="background-color:grey;height:2px;width:100%;"></div>
```



```{=html}
<div><pre><small><small>source: <a href="https://github.com/adabwana/support-vector-machine/blob/main/src/index.clj">src/index.clj</a></small></small></pre></div>
```
